spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGODB_URI}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

oauth:
  github:
    client-id: ${OAUTH_GITHUB_CLIENT_ID}
    client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
    redirect-uri: ${OAUTH_GITHUB_REDIRECT_URI}
    token-uri: ${OAUTH_GITHUB_TOKEN_URI}
    user-info-uri: ${OAUTH_GITHUB_USER_INFO_URI}

logging:
  level:
    org.hibernate.orm.connections: WARN
    org.hibernate.orm.deprecation: WARN

openai:
  api:
    key: ${OPENAI_API_KEY}