INSERT IGNORE INTO stacks (name, created_at, updated_at)
VALUES
    ('Java', NOW(), NOW()),
    ('Spring Boot', NOW(), NOW()),
    ('Kotlin', NOW(), NOW()),
    ('JavaScript', NOW(), NOW()),
    ('React', NOW(), NOW()),
    ('Node.js', NOW(), NOW()),
    ('Python', NOW(), NOW()),
    ('Django', NOW(), NOW()),
    ('Ruby', NOW(), NOW()),
    ('Rails', NOW(), NOW()),
    ('Go', NOW(), NOW()),
    ('Rust', NOW(), NOW()),
    ('PHP', NOW(), NOW()),
    ('Laravel', NOW(), NOW()),
    ('Swift', NOW(), NOW()),
    ('Flutter', NOW(), NOW()),
    ('TypeScript', NOW(), NOW()),
    ('GraphQL', NOW(), NOW()),
    ('Docker', NOW(), NOW()),
    ('Kubernetes', NOW(), NOW()),
    ('AWS', NOW(), NOW()),
    ('Azure', NOW(), NOW()),
    ('GCP', NOW(), NOW()),
    ('PostgreSQL', NOW(), NOW()),
    ('MySQL', NOW(), NOW()),
    ('MongoDB', NOW(), NOW()),
    ('Redis', NOW(), NOW()),
    ('Elasticsearch', NOW(), NOW()),
    ('Graphite', NOW(), NOW()),
    ('Prometheus', NOW(), NOW()),
    ('Grafana', NOW(), NOW()),
    ('Terraform', NOW(), NOW()),
    ('Ansible', NOW(), NOW()),
    ('CI/CD', NOW(), NOW()),
    ('Microservices', NOW(), NOW()),
    ('Serverless', NOW(), NOW()),
    ('Blockchain', NOW(), NOW()),
    ('Machine Learning', NOW(), NOW()),
    ('AI', NOW(), NOW()),
    ('Data Science', NOW(), NOW()),
    ('Big Data', NOW(), NOW()),
    ('DevOps', NOW(), NOW()),
    ('Agile', NOW(), NOW()),
    ('Scrum', NOW(), NOW()),
    ('Kanban', NOW(), NOW()),
    ('TDD', NOW(), NOW()),
    ('BDD', NOW(), NOW()),
    ('Pair Programming', NOW(), NOW()),
    ('Code Review', NOW(), NOW()),
    ('Version Control', NOW(), NOW()),
    ('Git', NOW(), NOW()),
    ('SVN', NOW(), NOW()),
    ('Jenkins', NOW(), NOW()),
    ('CircleCI', NOW(), NOW()),
    ('Travis CI', NOW(), NOW()),
    ('GitHub Actions', NOW(), NOW()),
    ('Bitbucket Pipelines', NOW(), NOW()),
    ('Selenium', NOW(), NOW()),
    ('Cypress', NOW(), NOW()),
    ('JUnit', NOW(), NOW()),
    ('Mockito', NOW(), NOW());